# .github/branch-protection.yml
rules:
  - name: Main branch protection
    branches: ["main"]
    required_status_checks:
      strict: true
      contexts:
        - "ci/build"
        - "ci/tests"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    enforce_admins: true
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false