trigger:
  - main

resources:
  - repo: self

variables:
  artifactName: 'coproxpert-api'

stages:
  - stage: Build
    displayName: Build and Publish Artifact
    jobs:
      - job: Build
        displayName: Build and Publish
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              go build -o $(Build.ArtifactStagingDirectory)/main $(Build.SourcesDirectory)/main.go
            displayName: 'Compile Project'

          - script: |
              zip -r $(Build.ArtifactStagingDirectory)/$(artifactName)-$(Build.BuildNumber).zip $(Build.ArtifactStagingDirectory)/main
            displayName: 'Compress Artifact'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: '$(artifactName)-$(Build.BuildNumber).zip'
