trigger:
  - main

resources:
  - repo: self

variables:
  artifactName: 'coproxpert-api'

stages:
  - stage: Build
    displayName: Build and Publish Artifact
    jobs:
      - job: Build
        displayName: Build and Publish
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              go build -o $(Build.BinariesDirectory)/main $(Build.SourcesDirectory)/main.go
            displayName: 'Compile Project'

          - task: ArchiveFiles@2
            displayName: 'Archive Files'
            inputs:
              rootFolderOrFile: '$(Build.BinariesDirectory)/main'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'bz2'
              archiveFile: '$(Build.BinariesDirectory)/$(artifactName)-$(Build.BuildNumber).tar.bz2'
              replaceExistingArchive: true

          - script: |
              rm -f $(Build.BinariesDirectory)/main
              displayName: 'Remove Compiled Binary'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.BinariesDirectory)'
              artifact: '$(artifactName)-$(Build.BuildNumber).tar.bz2'
          
