version: '3.9'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    ports:
      - "8888:5081"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__Default=Host=db;Port=5532;Database=cx_db;Username=cx_user;Password=Password
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=UTC
    volumes:
      - ./:/app
      - ~/.nuget/packages:/root/.nuget/packages
    working_dir: /app/CoproXpert.Api
    command: dotnet watch run

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=cx_db
      - POSTGRES_USER=cx_user
      - POSTGRES_PASSWORD=Password
      - TZ=UTC
    ports:
      - "5532:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    environment:
      - TZ=UTC
# 