version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copro_xpert_db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    restart: always

volumes:
  postgres_data:
