version: '3.9'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    ports:
      - "8888:5081"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__Default=Host=db;Port=5436;Database=mydatabase;Username=myuser;Password=mypassword
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ../:/app
      - ~/.nuget/packages:/root/.nuget/packages
    working_dir: /app/CoproXpert.Api
    command: dotnet watch run

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5436:5432"

  redis:
    image: redis