package models

// Report is a model for reports generated by the system about building's finances, maintenance, budget execution, etc.
type Report struct {
	ID          string `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	Description string `json:"description" gorm:"type:text;not null"`
	// BuildingID  uuid.UUID `json:"building_id" gorm:"type:uuid;not null"`
}
